#!/bin/ksh

QUADADDR=$1

HEXADDR=`echo $QUADADDR | nawk '{ split($0,q,"."); \
        printf("%.2x%.2x%.2x%.2x\n", q[1], q[2], q[3], q[4]); }'`

if [ -z "${HEXADDR}" ]; then
        echo "ERROR: Argument is not an IP quad: ${QUADADDR}"
        exit 1
fi

echo ${HEXADDR} | tr '[a-z]' '[A-Z]'

